# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name:  uMod CD Pipeline

on:
  push:
    branches:
      - main
  # Delete pull_request condition on merge
  pull_request:
    branches:
      - main
  workflow_dispatch:
      
jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x86]

    runs-on: windows-latest

    env:
      Configuration: Release
      Actions_Allow_Unsecure_Commands: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #https://stackoverflow.com/questions/61037714/how-to-install-an-old-version-of-the-direct-x-api-in-github-actions
    - name:  Config
      run:   echo ::set-env name=DXSDK_DIR::$HOME/cache/
      shell: bash

    - name: Cache
      id:   cache
      uses: actions/cache@v1
      with:
        path: ~/cache
        key:  cache

    - name:  Cache create
      if:    steps.cache.outputs.cache-hit != 'true'
      run:   |
        curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
        7z x _DX2010_.exe DXSDK/Include -o_DX2010_
        7z x _DX2010_.exe DXSDK/Lib/x86 -o_DX2010_
        mv _DX2010_/DXSDK $HOME/cache
        rm -fR _DX*_ _DX*_.exe
      shell: bash

    - name: Echo cache
      run: echo ${{ env.DXSDK_DIR }}

    - name: List dxsdk files
      run: |
        cd $HOME/cache
        ls
        cd Include
        ls
        cd ../Lib/x86
        ls

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build CMake Files
      run: cmake -S . -B build -A Win32

    - name: Build binaries
      run: cmake --build build --config Release

    - name: Retrieve version
      run: |
        $fileVersionInfo = (Get-ItemProperty -Path .\build\Release\uMod.dll).VersionInfo.FileVersion
        echo "::set-env name=Version::fileVersionInfo"

    - name: Publish release
      uses: Xotl/cool-github-releases@v1.1.8
      with:
        mode: update
        tag_name: v${{ env.Version }}
        release_name: Daybreak v${{ env.Version }}
        assets: .\build\Release\uMod.dll
        github_token: ${{ env.GITHUB_TOKEN }}
        replace_assets: true
        body_mrkdwn: ${{ env.Changelog }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    