# This continuous integration pipeline is triggered anytime a user pushes code to the repo.
# This pipeline builds the Wpf project, runs unit tests, then saves the MSIX build artifact.
name:  uMod CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
      
jobs:

  build:

    strategy:
      matrix:
        targetplatform: [x86]

    runs-on: windows-latest

    env:
      Configuration: Release
      Actions_Allow_Unsecure_Commands: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    #https://stackoverflow.com/questions/61037714/how-to-install-an-old-version-of-the-direct-x-api-in-github-actions
    - name:  Config
      run:   echo "DXSDK_DIR=$HOME/cache/" >> $GITHUB_ENV
      shell: bash

    - name: Cache
      id:   cache
      uses: actions/cache@v1
      with:
        path: ~/cache
        key:  cache

    - name:  Cache create
      if:    steps.cache.outputs.cache-hit != 'true'
      run:   |
        curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o _DX2010_.exe
        7z x _DX2010_.exe DXSDK/Include -o_DX2010_
        7z x _DX2010_.exe DXSDK/Lib/x86 -o_DX2010_
        mv _DX2010_/DXSDK $HOME/cache
        rm -fR _DX*_ _DX*_.exe
      shell: bash

    - name: Echo cache
      run: echo ${{ env.DXSDK_DIR }}

    - name: List dxsdk files
      run: |
        cd $HOME/cache
        ls
        cd Include
        ls
        cd ../Lib/x86
        ls

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build CMake Files
      run: cmake -S . -B build -A Win32 -DDIRECTX_SDK_INCLUDE_DIR="${{ env.DXSDK_DIR }}/Include" -DDIRECTX_SDK_LIB_DIR="${{ env.DXSDK_DIR }}/Lib/x86"
      env:
        DXSDK_DIR: ${{ env.DXSDK_DIR }}

    - name: Build binaries
      run: cmake --build build --config Release -DDIRECTX_SDK_INCLUDE_DIR="${{ env.DXSDK_DIR }}/Include" -DDIRECTX_SDK_LIB_DIR="${{ env.DXSDK_DIR }}/Lib/x86"
      env:
        DXSDK_DIR: ${{ env.DXSDK_DIR }}
    